// <auto-generated />
using System;
using ChamadosTI.Models.Modelo;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GestaoT.I.Migrations
{
    [DbContext(typeof(Contexto))]
    partial class ContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ChamadosTI.Models.Modelo.Chamados", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Identificacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("descricaoChamados")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("usuariosnomeUsuarioid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("usuariosnomeUsuarioid");

                    b.ToTable("Chamado");
                });

            modelBuilder.Entity("ChamadosTI.Models.Modelo.Perifericos", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("especificacaoPerifericos")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("nomePerifericos")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<float>("quantidadePerifericos")
                        .HasColumnType("real");

                    b.HasKey("id");

                    b.ToTable("Perifericos");
                });

            modelBuilder.Entity("ChamadosTI.Models.Modelo.Solicitacoes", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("nomeUsuarioSolicitacoesid")
                        .HasColumnType("int");

                    b.Property<int?>("perifericosSolicitacoesid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("nomeUsuarioSolicitacoesid");

                    b.HasIndex("perifericosSolicitacoesid");

                    b.ToTable("Solicitacoes");
                });

            modelBuilder.Entity("ChamadosTI.Models.Modelo.Usuario", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("maquinaUsuario")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("nomeUsuario")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("setorUsuario")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.HasKey("id");

                    b.ToTable("usuarioContext");
                });

            modelBuilder.Entity("ChamadosTI.Models.Modelo.Chamados", b =>
                {
                    b.HasOne("ChamadosTI.Models.Modelo.Usuario", "usuariosnomeUsuario")
                        .WithMany("chamados")
                        .HasForeignKey("usuariosnomeUsuarioid");

                    b.Navigation("usuariosnomeUsuario");
                });

            modelBuilder.Entity("ChamadosTI.Models.Modelo.Solicitacoes", b =>
                {
                    b.HasOne("ChamadosTI.Models.Modelo.Usuario", "nomeUsuarioSolicitacoes")
                        .WithMany("solicitacoes")
                        .HasForeignKey("nomeUsuarioSolicitacoesid");

                    b.HasOne("ChamadosTI.Models.Modelo.Perifericos", "perifericosSolicitacoes")
                        .WithMany("SolicitacoesPerifericos")
                        .HasForeignKey("perifericosSolicitacoesid");

                    b.Navigation("nomeUsuarioSolicitacoes");

                    b.Navigation("perifericosSolicitacoes");
                });

            modelBuilder.Entity("ChamadosTI.Models.Modelo.Perifericos", b =>
                {
                    b.Navigation("SolicitacoesPerifericos");
                });

            modelBuilder.Entity("ChamadosTI.Models.Modelo.Usuario", b =>
                {
                    b.Navigation("chamados");

                    b.Navigation("solicitacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
